// Generated by CoffeeScript 1.11.1
var getProto, isDev, isObjectLike;

getProto = require("getProto");

isDev = require("isDev");

module.exports = function(obj, key, defaultValue) {
  var result;
  if (isDev && !isObjectLike(obj)) {
    throw TypeError("'obj' must be object-like!");
  }
  if (isDev && typeof key !== "string") {
    throw TypeError("'key' must be a string!");
  }
  result = obj[key];
  delete obj[key];
  if (result === void 0) {
    return defaultValue;
  }
  return result;
};

isDev && (isObjectLike = function(value) {
  if (value) {
    if (value instanceof Object) {
      return true;
    }
    if (!getProto(value)) {
      return true;
    }
  }
  return false;
});
